# Generated by Django 3.2.8 on 2021-12-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_last_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_online',
        ),
    ]
